### ISSUE TITLE
Contextmenu frame is always on the left, I want to put it just below the view on right side of the screen.

### ISSUE THREAD

**Issue by pushkar-7** [umerjabbar/ContextMenuSwift#8]
![simulator_screenshot_9CCDFA4C-AE7B-4D29-BF3C-255730AE59F9](https://user-images.githubusercontent.com/111354253/190363909-c7574070-c4da-46bd-85b9-0ef3d42ffeaa.png)

**Comment by KhaledHoSobh** [comment]
yup same thing with me I need view frame in right but frame always in left

**Comment by hemant-avaal** [comment]
Did you get any solution to this ? Am trying the same thing

**Comment by KhaledHoSobh** [comment]
@hemant-avaal  
No I haven't found a solution yet, I skipped it

**Comment by pushkar-7** [comment]
@hemant-avaal , @KhaledHoSobh hi , i got one solution for this:
1. create a uiview and connect Iboutlet in controller class.
2. add a button in that view.
3. in action of that button
use :

 self.contextMenu.showMenu(viewTargeted: contextImageTargetView(your view's outlet), delegate: self)
 
 or you can connect me over pushkerpandey7@gmail.com i will help

**Comment by umerjabbar** [comment]
@hemant-avaal @pushkar-7
I will add a feature that allows users to select the primary direction of the menu.

**Comment by KhaledHoSobh** [comment]
@pushkar-7  hi , I will try your solution 

thanks

**Comment by umerjabbar** [comment]
@KhaledHoSobh @hemant-avaal @pushkar-7 
Check out the new version uploaded. I have only updated the swift package.
https://github.com/umerjabbar/ContextMenuSwift/releases/tag/2.0.0

**Comment by umerjabbar** [comment]
@KhaledHoSobh let me know, if this is what you wanted.
Thank you
