### ISSUE TITLE
Movement of targetedView is going beyond safe area in iOS 17.0

### ISSUE THREAD

**Issue by hemant-avaal** [umerjabbar/ContextMenuSwift#9]
The movement of the targetedView goes beyond the safe area (goes behind dynamic island) in case of long list of options. Although i would like to know if it is possible to restrict the movement of targetedView and just show the dropdown menus only. (I know a better option is to implement a tableview but this lib goes well with implementation throughout the project)

iOS 17.0
Device : Simulator iPhone 15 pro

https://github.com/umerjabbar/ContextMenuSwift/assets/97078292/5f05d748-3679-4a17-92ac-1ddebad9396b

Thankyou

**Comment by umerjabbar** [comment]
@hemant-avaal 
Thank you for reaching out here. I have fixed this issue and it is live as 2.0.1 version.
Let me know if you need any help.

**Comment by hemant-avaal** [comment]
@umerjabbar thankyou for providing the solution. It solves the safe are issue. Can you suggest how can i restrict the movement of targetedView in case of long option list ?
